import type { Meeting, MeetingPatch } from './meeting';
import type { AppSettings, Capabilities, CaptureSnapshot } from './capture';
import type { CalendarEvent, CalendarSnapshot } from './calendar';
import type { AskRequest, AssistantAnswer } from './assistant';
import type { ShareOptions, SharePreview } from './share';
export type { CalendarEvent } from './calendar';
import type { DetectionSnapshot } from './meeting-detection';

export type SaveStatus = { state: 'saved' | 'saving' | 'error'; message?: string };
export type NotebookSnapshot = { meetings: Meeting[]; unreadable: string[]; platform: string };
export type RuntimeSnapshot = { settings: AppSettings; capabilities: Capabilities; keySaved: boolean; assistantKeySaved: boolean; capture: CaptureSnapshot; detection: DetectionSnapshot };
export interface NotebookAPI {
  load(): Promise<NotebookSnapshot>;
  create(kind: 'meeting' | 'scratchpad'): Promise<Meeting>;
  update(id: string, patch: MeetingPatch): Promise<void>;
  import(): Promise<Meeting | null>;
  export(id: string, format: 'json' | 'markdown'): Promise<boolean>;
  copy(id: string): Promise<void>;
  showStorage(): Promise<void>;
  runtime(): Promise<RuntimeSnapshot>;
  saveSettings(settings: AppSettings): Promise<RuntimeSnapshot>;
  saveKey(key: string): Promise<boolean>;
  saveAssistantKey(key: string): Promise<boolean>;
  ask(request: AskRequest): Promise<void>;
  assistantThread(meetingId: string): Promise<AssistantAnswer[]>;
  stopAnswer(requestId: string): Promise<void>;
  clearAssistant(meetingId: string): Promise<void>;
  copyAnswer(meetingId: string, requestId: string, draft?: string): Promise<void>;
  previewShare(meetingId: string, options: ShareOptions): Promise<SharePreview>;
  deliverShare(token: string, method: 'copy' | 'export'): Promise<boolean>;
  requestAccessibility(): Promise<RuntimeSnapshot>;
  startCapture(meetingId: string, purpose: 'meeting' | 'dictation'): Promise<void>;
  stopCapture(): Promise<void>;
  pauseCapture(): Promise<void>;
  resumeCapture(): Promise<void>;
  companion(action: 'dictation' | 'meeting' | 'scratchpad' | 'notebook' | 'hover' | 'leave'): Promise<void>;
  summarize(id: string): Promise<void>;
  importAudio(): Promise<Meeting | null>;
  calendar(): Promise<CalendarEvent[]>;
  calendarSnapshot(): Promise<CalendarSnapshot>;
  connectCalendar(): Promise<CalendarSnapshot>;
  disconnectCalendar(): Promise<void>;
  openCalendarApp(): Promise<void>;
  setMeetingDetection(enabled: boolean): Promise<RuntimeSnapshot>;
  dismissMeetingPrompt(id: string): Promise<void>;
  startDetectedMeeting(id: string): Promise<void>;
  refreshCalendar(): Promise<CalendarSnapshot>;
  joinEvent(id: string): Promise<void>;
  prepareEvent(event: CalendarEvent): Promise<Meeting>;
  onCapture(callback: (snapshot: CaptureSnapshot) => void): () => void;
  onMeeting(callback: (meeting: Meeting, fields: (keyof Meeting)[]) => void): () => void;
  onRuntime(callback: (snapshot: RuntimeSnapshot) => void): () => void;
  onCalendar(callback: (snapshot: CalendarSnapshot) => void): () => void;
  onAssistant(callback: (answer: AssistantAnswer) => void): () => void;
  onSelect(callback: (id: string) => void): () => void;
  onSaveStatus(callback: (status: SaveStatus) => void): () => void;
  onCommand(callback: (command: 'new' | 'import' | 'search') => void): () => void;
}
declare global { interface Window { chirpberry: NotebookAPI } }
